spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_SERVER_URL}/realms/bank
  cloud:
    consul:
      host: ${CONSUL_HOST}
      discovery:
        service-name: api-gateway
    gateway:
      server:
        webflux:
          routes:
            - id: account-service
              uri: ${ACCOUNT_SERVICE_URL}
              predicates:
                - Path=/account/**
              filters:
                - name: JwtTokenRelay
            - id: cash-service
              uri: ${CASH_SERVICE_URL}
              predicates:
                - Path=/cash/**
              filters:
                - name: JwtTokenRelay
            - id: transfer-service
              uri: ${TRANSFER_SERVICE_URL}
              predicates:
                - Path=/transfer/**
              filters:
                - name: JwtTokenRelay