spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_SERVER_URL}/realms/bank
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: account-service
              uri: ${ACCOUNT_SERVICE_URL}
              predicates:
                - Path=/account/**
              filters:
                - name: JwtTokenRelay