spring:
  cloud:
    consul:
      host: ${CONSUL_HOST}
      discovery:
        service-name: frontend-ui
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: bank-frontend
            client-secret: ${BANK_FRONT_UI_SECRET}
            scope: openid, profile, email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          keycloak:
            issuer-uri: ${AUTH_SERVER_URL}/realms/bank

gateway:
  url: ${API_GATEWAY_URL}