spring:
  cloud:
    consul:
      host: ${CONSUL_HOST}
      discovery:
        service-name: notification-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_SERVER_URL}/realms/bank

logging:
  level:
    com.tarasov.bank.notification.service: INFO