spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_SERVER_URL}/realms/bank
      client:
        provider:
          keycloak:
            issuer-uri: ${AUTH_SERVER_URL}/realms/bank
        registration:
          transfer-service:
            provider: keycloak
            authorization-grant-type: client_credentials
            client-id: transfer-service
            client-secret: ${TRANSFER_SERVICE_SECRET}

notification-service:
  url: ${NOTIFICATION_SERVICE_URL}

account-service:
  url: ${ACCOUNT_SERVICE_URL}